import { NextRequest, NextResponse } from 'next/server';
import seed from '../../../data/deals.json';
export const dynamic='force-dynamic';
const DESTS:any={NRT:'東京 NRT',KIX:'大阪 KIX',FUK:'福岡 FUK',OKA:'沖繩 OKA',ICN:'首爾 ICN',PUS:'釜山 PUS',HKG:'香港 HKG',BKK:'曼谷 BKK',SIN:'新加坡 SIN',KUL:'吉隆坡 KUL',SGN:'胡志明 SGN',DAD:'峴港 DAD',SYD:'雪梨 SYD',MEL:'墨爾本 MEL',BNE:'布里斯本 BNE',PER:'伯斯 PER'};
const ORIGINS:any={TPE:'台北桃園 TPE',KHH:'高雄 KHH',TSA:'台北松山 TSA'};
function pairs<T>(arr:T[]){const out:[T,T][]=[]; for(let i=0;i<arr.length;i++)for(let j=i+1;j<arr.length;j++)out.push([arr[i],arr[j]]); return out}
function gfUrl(legs:any[]){const q=encodeURIComponent(JSON.stringify(legs));return `https://www.google.com/travel/flights/search?flight_type=multi_city&multi_city_json=${q}`}
function region(a:string,b:string){if(['NRT','KIX','FUK','OKA'].includes(a)&&['NRT','KIX','FUK','OKA'].includes(b))return '日本'; if(['ICN','PUS'].includes(a)&&['ICN','PUS'].includes(b))return '韓國'; if(['SYD','MEL','BNE','PER'].includes(a)||['SYD','MEL','BNE','PER'].includes(b))return '澳洲'; return '香港/東南亞'}
async function searchApi(origin:string,a:string,b:string,key:string){const legs=[{departure_id:origin,arrival_id:a,outbound_date:'2026-09-15'},{departure_id:a,arrival_id:origin,outbound_date:'2026-09-20'},{departure_id:origin,arrival_id:b,outbound_date:'2026-10-15'},{departure_id:b,arrival_id:origin,outbound_date:'2026-10-20'}];const params=new URLSearchParams({engine:'google_flights',api_key:key,flight_type:'multi_city',multi_city_json:JSON.stringify(legs),currency:'TWD',hl:'zh-tw'});const res=await fetch(`https://www.searchapi.io/api/v1/search?${params}`,{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error||`SearchApi ${res.status}`);const fs=[...(data.best_flights||[]),...(data.other_flights||[])];const cheapest=fs.filter((f:any)=>f.price).sort((x:any,y:any)=>x.price-y.price)[0];return {price:cheapest?.price??null,airlines:cheapest?.flights?.map((f:any)=>f.airline).filter(Boolean)??[],googleFlightsUrl:data.search_metadata?.request_url,htmlUrl:data.search_metadata?.html_url,legs}}
export async function POST(req:NextRequest){const key=process.env.SEARCHAPI_API_KEY;if(!key)return NextResponse.json({error:'missing SEARCHAPI_API_KEY on Vercel/local env'}, {status:400});const body=await req.json();const origins=(body.origins||[]).filter((x:string)=>ORIGINS[x]).slice(0,2);const destinations=(body.destinations||[]).filter((x:string)=>DESTS[x]).slice(0,8);const candidates=[] as any[];for(const o of origins)for(const [a,b] of pairs(destinations))candidates.push([o,a,b]);const limited=candidates.slice(0,20);const deals=[] as any[];let used=0;for(const [o,a,b] of limited){used++;const sepA=(seed as any).roundtrips?.[o]?.[a]?.price||0;const sepB=(seed as any).roundtrips?.[o]?.[b]?.price||0;const separate=sepA&&sepB?sepA+sepB:0;const r=await searchApi(o,a,b,key);deals.push({id:`live-${o}-${a}-${b}`,region:region(a,b),confidence:r.price&&separate&&r.price/separate<=.9?'medium':'watch',origin:o,baseRoute:`${ORIGINS[o]} ↔ ${DESTS[a]}`,comboRoute:`${ORIGINS[o]} ↔ ${DESTS[a]} + ${ORIGINS[o]} ↔ ${DESTS[b]}`,dates:'2026-09-15/09-20 + 2026-10-15/10-20',basePrice:sepA||0,separateTotalPrice:separate||r.price||0,bundledPrice:r.price,comboPrice:r.price||separate,currency:'TWD',airlines:Array.from(new Set(r.airlines)).slice(0,6),why:separate?`使用者觸發 SearchApi 查得一起買約 NT$${r.price?.toLocaleString('zh-TW')}；分開買估算約 NT$${separate.toLocaleString('zh-TW')}。`:'已查到一起買價；分開買基準尚未在快取中。',risks:['SearchApi/Google Flights 候選價不保證最終可出票','需點進 Google Flights 或供應商付款頁再次確認','多城市與分開票的行李/退改規則可能不同'],verifyUrl:'https://www.google.com/travel/flights',googleFlightsUrl:r.googleFlightsUrl||gfUrl(r.legs),searchApiHtmlUrl:r.htmlUrl,source:'user-triggered-searchapi'});}return NextResponse.json({apiCallsUsed:used,deals});}
