import seed from '../data/deals.json';

type Deal = typeof seed.deals[number];
function money(n:number,c='TWD'){return new Intl.NumberFormat('zh-TW',{style:'currency',currency:c,maximumFractionDigits:0}).format(n)}
function ratio(d:Deal){return d.comboPrice/d.basePrice}
function score(d:Deal){const r=ratio(d); if(r<=1.08)return 92; if(r<=1.15)return 82; if(r<=1.25)return 68; if(r<=1.6)return 45; return 25}
function badge(c:string){return c==='high'?'接近同價':c==='medium'?'值得查證':c==='watch'?'偏貴觀察':'不便宜'}
function verdict(d:Deal){const r=ratio(d); if(r<=1.08)return '幾乎同價：很值得查'; if(r<=1.15)return '接近同價：可查證'; if(r<=1.25)return '有機會：但不算神價'; if(r<=1.6)return '偏貴：除非剛好需要兩趟'; return '不便宜：本輪只是留底'}
export default function Page(){const deals=[...seed.deals].sort((a,b)=>score(b)-score(a));return <main>
 <section className="hero"><div className="kicker">Fare Anomaly Radar · 四腳機票情報</div><h1>快速看到<br/>哪些機票值得買</h1><p>低頻掃描台灣出發的候選航線，找出「多買一趟 / 四腳組合」是否只比第一趟基準來回多一點。目前使用本地低頻 Google Flights scraper 產生候選；不是官方 API，購買前必須人工查證。</p><div className="stats"><div><b>{deals.length}</b><span>本輪候選</span></div><div><b>{seed.scanScope.threshold}</b><span>異常門檻</span></div><div><b>{seed.scanScope.origins.join(' / ')}</b><span>出發地</span></div><div><b>{seed.scanScope.regions.join(' / ')}</b><span>區域</span></div></div></section>
 <section className="notice"><b>怎麼看：</b>每張卡都拿「基準來回」當分母，例如高雄↔曼谷；再看「四腳組合」= 基準來回 + 第二組來回，例如再加香港。倍率 1.10x 代表多買一趟只貴 10%；越接近 1.00x 越值得查。<br/><b>資料狀態：</b>{seed.scannerNote}</section>
 <section className="toolbar"><a href="https://www.google.com/travel/flights" target="_blank">打開 Google Flights 查證</a><span>已加入：高雄 KHH、東南亞、澳洲；目前顯示所有候選；真正便宜要看「多買第二趟只多多少」。</span></section>
 {deals.length===0?<section className="notice"><b>本輪沒有命中四角異常。</b> Scanner 已正常執行，但沒有找到 combo/base 接近門檻的候選；請擴大日期或目的地池。</section>:null}<section className="deals">{deals.map(d=><article className={`deal ${d.confidence}`} key={d.id}><div className="dealTop"><span className="region">{d.region}</span><span className="conf">{badge(d.confidence)}</span></div><h2>{d.comboRoute}</h2><p className="base">比較基準：如果你本來只想買 <b>{d.baseRoute}</b>，那多加第二趟後總價變多少？</p><div className="verdict">{verdict(d)}</div><div className="priceGrid"><div><span>① 基準來回</span><b>{money(d.basePrice,d.currency)}</b></div><div><span>② 四腳組合總價</span><b>{money(d.comboPrice,d.currency)}</b></div><div><span>多買第二趟只多</span><b>{money(d.comboPrice-d.basePrice,d.currency)}</b></div><div><span>② / ① 倍率</span><b>{ratio(d).toFixed(2)}x</b></div></div><div className="meter"><i style={{width:`${score(d)}%`}}/><em>{score(d)} 異常分</em></div><p className="why">{d.why}</p><div className="meta"><span>{d.origin}</span><span>{d.dates}</span><span>{d.airlines.join(' / ')}</span></div><details><summary>購買前風險檢查</summary><ul>{d.risks.map(r=><li key={r}>{r}</li>)}</ul></details><a className="cta" href={d.verifyUrl} target="_blank">查證這張票</a></article>)}</section>
 <section className="how"><div><span>How it works</span><h2>它會怎麼幫你找票？</h2></div><ol><li>掃描 TPE / TSA / KHH 出發的熱門目的地。</li><li>先找第一趟基準來回，例如 TPE↔NRT。</li><li>再加第二趟來回，形成四腳組合，例如 TPE↔NRT + TPE↔KIX。</li><li>比較組合總價 / 基準來回價；越接近 1.00x，代表第二趟越像白送。</li><li>只把候選拿來提示，最後仍回 Google Flights 或航司官網查證。</li></ol></section>
 <footer>不出票、不保證價格；這是便宜機票情報雷達。接入合法航班 API 後才會顯示 live deal。</footer>
 </main>}
