'use client';
import seed from '../data/deals.json';
import { useMemo, useState } from 'react';

type Deal = typeof seed.deals[number] & { separateTotalPrice?: number; bundledPrice?: number|null; googleFlightsUrl?: string; searchApiHtmlUrl?: string; source?: string };
const ORIGINS=[{code:'TPE',label:'台北桃園'},{code:'KHH',label:'高雄'},{code:'TSA',label:'台北松山',disabled:true}];
const DESTS=[['NRT','東京'],['KIX','大阪'],['FUK','福岡'],['OKA','沖繩'],['ICN','首爾'],['PUS','釜山'],['HKG','香港'],['BKK','曼谷'],['SIN','新加坡'],['KUL','吉隆坡'],['SGN','胡志明'],['DAD','峴港'],['SYD','雪梨'],['MEL','墨爾本'],['BNE','布里斯本'],['PER','伯斯']].map(([code,label])=>({code,label}));
function money(n:number,c='TWD'){return new Intl.NumberFormat('zh-TW',{style:'currency',currency:c,maximumFractionDigits:0}).format(n)}
function separateTotal(d:Deal){return d.separateTotalPrice ?? d.comboPrice}
function bundled(d:Deal){return d.bundledPrice ?? null}
function ratio(d:Deal){const b=bundled(d); return b? b/separateTotal(d) : 9}
function savings(d:Deal){const b=bundled(d); return b? separateTotal(d)-b : null}
function score(d:Deal){const r=ratio(d); if(r<=.75)return 96; if(r<=.9)return 84; if(r<=1.03)return 68; return 35}
function verdict(d:Deal){const b=bundled(d); if(!b)return '待查：尚未打 API 查一起買價'; const r=ratio(d); if(r<=.75)return '強烈異常：一起買省很多'; if(r<=.9)return '值得買：一起買明顯便宜'; if(r<=1.03)return '接近同價：可查證'; return '一起買沒有優勢'}
function regionOf(code:string){if(['NRT','KIX','FUK','OKA'].includes(code))return '日本'; if(['ICN','PUS'].includes(code))return '韓國'; if(['SYD','MEL','BNE','PER'].includes(code))return '澳洲'; return '香港/東南亞'}
function combos<T>(arr:T[]){const out:[T,T][]=[]; for(let i=0;i<arr.length;i++)for(let j=i+1;j<arr.length;j++)out.push([arr[i],arr[j]]); return out}
export default function Page(){
 const [origins,setOrigins]=useState(['TPE','KHH']); const [dests,setDests]=useState(['NRT','KIX','ICN','BKK','HKG','SYD']); const [results,setResults]=useState<Deal[]>(seed.deals as Deal[]); const [loading,setLoading]=useState(false); const [msg,setMsg]=useState('目前顯示最近一次掃描結果。勾選後按搜尋才會使用 API。');
 const planned=useMemo(()=>origins.length*combos(dests).length,[origins,dests]);
 function toggle(v:string,setter:(x:string[])=>void,list:string[]){setter(list.includes(v)?list.filter(x=>x!==v):[...list,v])}
 async function search(){setLoading(true); setMsg('查詢中：先產生四角組合，再用 SearchApi 查一起買價。'); try{const r=await fetch('/api/search-deals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({origins,destinations:dests})}); const data=await r.json(); if(!r.ok) throw new Error(data.error||'search failed'); setResults(data.deals||[]); setMsg(`完成：使用 ${data.apiCallsUsed??0} 次 API，產生 ${data.deals?.length??0} 筆候選。`)}catch(e:any){setMsg(`查詢失敗：${e.message}`)}finally{setLoading(false)}}
 return <main><section className="hero"><div className="kicker">Fare Anomaly Radar · 使用者觸發查詢版</div><h1>勾選想去的地方<br/>再找四角票</h1><p>選你能接受的出發地與想去的目的地，按搜尋後才消耗 API 額度查「一起買 / 多城市」價格。不是即時全網搜尋；每次會限制查詢組數，避免浪費免費額度。</p><div className="stats"><div><b>{results.length}</b><span>目前結果</span></div><div><b>{planned}</b><span>預估組合</span></div><div><b>{origins.join(' / ')}</b><span>出發地</span></div><div><b>{dests.length}</b><span>目的地</span></div></div></section>
 <section className="searchBox"><div><h2>1. 可接受的出發地</h2><div className="chips">{ORIGINS.map(o=><button key={o.code} disabled={o.disabled} onClick={()=>toggle(o.code,setOrigins,origins)} className={origins.includes(o.code)?'on':''}>{o.label} {o.code}{o.disabled?' · soon':''}</button>)}</div></div><div><h2>2. 想去的地方（可複選）</h2><div className="chips dests">{DESTS.map(d=><button key={d.code} onClick={()=>toggle(d.code,setDests,dests)} className={dests.includes(d.code)?'on':''}>{d.label} {d.code}</button>)}</div></div><div className="searchFoot"><span>{planned>20?'⚠️ 組合偏多，會只查前 20 組。':'每兩個目的地會形成一組四角候選。'}</span><button className="primary" disabled={loading||origins.length===0||dests.length<2} onClick={search}>{loading?'搜尋中…':'搜尋四角票'}</button></div></section>
 <section className="notice"><b>狀態：</b>{msg}<br/><b>怎麼買：</b>卡片若有 Google Flights 連結，會帶到該組多城市查證頁；若之後取得 booking options，才會顯示實際供應商購買選項。</section>
 {results.length===0?<section className="notice"><b>沒有結果。</b> 請多選幾個目的地，或換出發地。</section>:null}<section className="deals">{[...results].sort((a,b)=>score(b)-score(a)).map(d=><article className={`deal ${d.bundledPrice?'medium':'watch'}`} key={d.id}><div className="dealTop"><span className="region">{d.region||regionOf(d.origin)}</span><span className="conf">{d.bundledPrice?'已查一起買價':'待查一起買價'}</span></div><h2>{d.comboRoute}</h2><p className="base">比較：分開買兩組 vs 一起買 / 多城市。</p><div className="verdict">{verdict(d)}</div><div className="priceGrid"><div><span>分開買兩組總價</span><b>{money(separateTotal(d),d.currency)}</b></div><div><span>一起買 / 多城市</span><b>{bundled(d)?money(bundled(d)!,d.currency):'待查'}</b></div><div><span>可省</span><b>{savings(d)!==null?money(savings(d)!,d.currency):'待查'}</b></div><div><span>省錢倍率</span><b>{bundled(d)?ratio(d).toFixed(2)+'x':'待查'}</b></div></div><div className="meter"><i style={{width:`${score(d)}%`}}/><em>{score(d)} 異常分</em></div><p className="why">{d.why}</p><div className="meta"><span>{d.origin}</span><span>{d.dates}</span><span>{d.airlines?.join(' / ')||'待查'}</span></div><details><summary>購買前風險檢查</summary><ul>{d.risks.map(r=><li key={r}>{r}</li>)}</ul></details><div className="actions"><a className="cta" href={d.googleFlightsUrl||d.verifyUrl} target="_blank">查看 Google Flights</a>{d.searchApiHtmlUrl?<a className="ghost" href={d.searchApiHtmlUrl} target="_blank">SearchApi 快照</a>:null}</div></article>)}</section>
 <section className="how"><div><span>How it works</span><h2>查詢怎麼運作？</h2></div><ol><li>使用者勾選出發地與多個目的地。</li><li>系統把目的地兩兩配對成四角候選。</li><li>按搜尋後才打 SearchApi 查多城市 bundled price。</li><li>卡片比較「分開買」與「一起買」，有連結可回 Google Flights 查證。</li></ol></section><footer>不出票、不保證價格；最終以 Google Flights / 航司 / OTA 付款頁為準。</footer></main>}
